name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Update status
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
            chat: ${{ secrets.TELEGRAM_TO }} # user id or channel name secret
            token: ${{ secrets.TELEGRAM_TOKEN }} # token secret
            status: ${{ job.status }} # do not modify this line